# Generated by Django 3.0.8 on 2020-07-29 21:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WantedItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Entity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedItemArray',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=1000000)),
                ('names', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=10000000)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Entity')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wanteditem',
            constraint=models.UniqueConstraint(fields=('entity', 'item'), name='entity_need_item'),
        ),
    ]
