# Generated by Django 3.0.8 on 2020-07-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemWithIndex',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
            ],
        ),
    ]
